### ISSUE TITLE
What's with the strange name?

### ISSUE THREAD

**Issue by rstacruz** [JohnPittman/http-js#1]

**Comment by JohnPittman** [comment]
There's obviously a story behind it. What's more magical than a dinosaur? A
chicken dinosaur. If something works like magic then the only way to
explain it is a chicken dinosaur. This all evolved from my last job with a
coworker. Cheers. =)

John R. Pittman |
<https://plus.google.com/u/0/100394734061909211307/about/p/pub>

johnrichardpittman@gmail.com

mobile: 561-460-2051
